// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// ClusterInfo represents status of a resource bundle rollout for a cluster.
public struct ClusterInfo: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. gkehub membership of target cluster
  public var membership: Swift.String = Swift.String()

  /// Output only. Desired state for the resource bundle.
  public var desired: ResourceBundleDeploymentInfo? = nil

  /// Output only. Initial state of the resource bundle prior to the deployment.
  public var initial: ResourceBundleDeploymentInfo? = nil

  /// Output only. Current state of the resource bundle.
  public var current: ResourceBundleDeploymentInfo? = nil

  /// Output only. State of the rollout for the cluster.
  public var state: ClusterInfo.State = ClusterInfo.State()

  /// Output only. Unordered list. Messages convey additional information related
  /// to the deployment.
  public var messages: [Swift.String] = []

  /// Output only. Timestamp when reconciliation starts.
  public var startTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Timestamp when reconciliation ends.
  public var endTime: GoogleWKT.WKTTimestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ClusterInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ClusterInfo().with { $0.membership = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let membership = CodingKeys(stringValue: "membership")
    static let desired = CodingKeys(stringValue: "desired")
    static let initial = CodingKeys(stringValue: "initial")
    static let current = CodingKeys(stringValue: "current")
    static let state = CodingKeys(stringValue: "state")
    static let messages = CodingKeys(stringValue: "messages")
    static let startTime = CodingKeys(stringValue: "startTime")
    static let endTime = CodingKeys(stringValue: "endTime")

    static let _knownKeys: Set<Swift.String> = [
      "membership",
      "desired",
      "initial",
      "current",
      "state",
      "messages",
      "startTime",
      "endTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .membership) {
      self.membership = value
    }
    self.desired = try container.decodeIfPresent(
      ResourceBundleDeploymentInfo.self, forKey: .desired)
    self.initial = try container.decodeIfPresent(
      ResourceBundleDeploymentInfo.self, forKey: .initial)
    self.current = try container.decodeIfPresent(
      ResourceBundleDeploymentInfo.self, forKey: .current)
    if let value = try container.decodeIfPresent(ClusterInfo.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .messages) {
      self.messages = value
    }
    self.startTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .startTime)
    self.endTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .endTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.membership, forKey: .membership)
    try container.encodeIfPresent(self.desired, forKey: .desired)
    try container.encodeIfPresent(self.initial, forKey: .initial)
    try container.encodeIfPresent(self.current, forKey: .current)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.messages, forKey: .messages)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// State of the rollout for the cluster.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Hashable, Sendable {
    /// Unspecified state.
    case unspecified
    /// Waiting state.
    case waiting
    /// In progress state.
    case inProgress
    /// Stalled state.
    case stalled
    /// Completed state.
    case completed
    /// Aborted state.
    case aborted
    /// Cancelled state.
    case cancelled
    /// Error state.
    case error
    /// Unchanged state.
    case unchanged
    /// Skipped state.
    case skipped
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .waiting: return 1
      case .inProgress: return 2
      case .stalled: return 3
      case .completed: return 4
      case .aborted: return 5
      case .cancelled: return 6
      case .error: return 7
      case .unchanged: return 8
      case .skipped: return 9
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .waiting: return "WAITING"
      case .inProgress: return "IN_PROGRESS"
      case .stalled: return "STALLED"
      case .completed: return "COMPLETED"
      case .aborted: return "ABORTED"
      case .cancelled: return "CANCELLED"
      case .error: return "ERROR"
      case .unchanged: return "UNCHANGED"
      case .skipped: return "SKIPPED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "WAITING": self = .waiting
      case "IN_PROGRESS": self = .inProgress
      case "STALLED": self = .stalled
      case "COMPLETED": self = .completed
      case "ABORTED": self = .aborted
      case "CANCELLED": self = .cancelled
      case "ERROR": self = .error
      case "UNCHANGED": self = .unchanged
      case "SKIPPED": self = .skipped
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .waiting
      case 2: self = .inProgress
      case 3: self = .stalled
      case 4: self = .completed
      case 5: self = .aborted
      case 6: self = .cancelled
      case 7: self = .error
      case 8: self = .unchanged
      case 9: self = .skipped
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .waiting: return try container.encode("WAITING")
      case .inProgress: return try container.encode("IN_PROGRESS")
      case .stalled: return try container.encode("STALLED")
      case .completed: return try container.encode("COMPLETED")
      case .aborted: return try container.encode("ABORTED")
      case .cancelled: return try container.encode("CANCELLED")
      case .error: return try container.encode("ERROR")
      case .unchanged: return try container.encode("UNCHANGED")
      case .skipped: return try container.encode("SKIPPED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.configdelivery.v1.ClusterInfo"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
