// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// ConfigDelivery service manages the deployment of kubernetes configuration to
/// a fleet of kubernetes clusters.
///
/// @Snippet(path: "ConfigDeliveryQuickstart")
public final class ConfigDeliveryClient: Clients.ConfigDeliveryProtocol, Sendable {
  let inner: any Clients.ConfigDeliveryStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `ConfigDeliveryClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.ConfigDeliveryStub = try Clients.ConfigDeliveryTransport(options)
    inner = Clients.ConfigDeliveryRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ConfigDeliveryLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists ResourceBundles in a given project and location.
  ///
  /// @Snippet(path: "ConfigDelivery_ListResourceBundles")
  public func listResourceBundles(
    request: ListResourceBundlesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConfigDeliveryV1.ListResourceBundlesResponse {
    try await self.inner.listResourceBundles(request: request, options: options)
  }

  /// Gets details of a single ResourceBundle.
  ///
  /// @Snippet(path: "ConfigDelivery_GetResourceBundle")
  public func getResourceBundle(
    request: GetResourceBundleRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConfigDeliveryV1.ResourceBundle {
    try await self.inner.getResourceBundle(request: request, options: options)
  }

  /// Creates a new ResourceBundle in a given project and location.
  ///
  /// @Snippet(path: "ConfigDelivery_CreateResourceBundle")
  public func createResourceBundle(
    request: CreateResourceBundleRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createResourceBundle(request: request, options: options)
  }

  /// Creates a new ResourceBundle in a given project and location.
  ///
  /// @Snippet(path: "ConfigDelivery_CreateResourceBundle")
  public func createResourceBundlePollingUntilDone(
    request: CreateResourceBundleRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<ResourceBundle> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<ResourceBundle>.State in
      return try op._extractStatus(ResourceBundle.self)
    }
    let rawOp = try await self.createResourceBundle(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<ResourceBundle>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the parameters of a single ResourceBundle.
  ///
  /// @Snippet(path: "ConfigDelivery_UpdateResourceBundle")
  public func updateResourceBundle(
    request: UpdateResourceBundleRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateResourceBundle(request: request, options: options)
  }

  /// Updates the parameters of a single ResourceBundle.
  ///
  /// @Snippet(path: "ConfigDelivery_UpdateResourceBundle")
  public func updateResourceBundlePollingUntilDone(
    request: UpdateResourceBundleRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<ResourceBundle> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<ResourceBundle>.State in
      return try op._extractStatus(ResourceBundle.self)
    }
    let rawOp = try await self.updateResourceBundle(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<ResourceBundle>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single ResourceBundle.
  ///
  /// @Snippet(path: "ConfigDelivery_DeleteResourceBundle")
  public func deleteResourceBundle(
    request: DeleteResourceBundleRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteResourceBundle(request: request, options: options)
  }

  /// Deletes a single ResourceBundle.
  ///
  /// @Snippet(path: "ConfigDelivery_DeleteResourceBundle")
  public func deleteResourceBundlePollingUntilDone(
    request: DeleteResourceBundleRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteResourceBundle(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists FleetPackages in a given project and location.
  ///
  /// @Snippet(path: "ConfigDelivery_ListFleetPackages")
  public func listFleetPackages(
    request: ListFleetPackagesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConfigDeliveryV1.ListFleetPackagesResponse {
    try await self.inner.listFleetPackages(request: request, options: options)
  }

  /// Gets details of a single FleetPackage.
  ///
  /// @Snippet(path: "ConfigDelivery_GetFleetPackage")
  public func getFleetPackage(
    request: GetFleetPackageRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConfigDeliveryV1.FleetPackage {
    try await self.inner.getFleetPackage(request: request, options: options)
  }

  /// Creates a new FleetPackage in a given project and location.
  ///
  /// @Snippet(path: "ConfigDelivery_CreateFleetPackage")
  public func createFleetPackage(
    request: CreateFleetPackageRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createFleetPackage(request: request, options: options)
  }

  /// Creates a new FleetPackage in a given project and location.
  ///
  /// @Snippet(path: "ConfigDelivery_CreateFleetPackage")
  public func createFleetPackagePollingUntilDone(
    request: CreateFleetPackageRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<FleetPackage> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<FleetPackage>.State in
      return try op._extractStatus(FleetPackage.self)
    }
    let rawOp = try await self.createFleetPackage(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<FleetPackage>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the parameters of a single FleetPackage.
  ///
  /// @Snippet(path: "ConfigDelivery_UpdateFleetPackage")
  public func updateFleetPackage(
    request: UpdateFleetPackageRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateFleetPackage(request: request, options: options)
  }

  /// Updates the parameters of a single FleetPackage.
  ///
  /// @Snippet(path: "ConfigDelivery_UpdateFleetPackage")
  public func updateFleetPackagePollingUntilDone(
    request: UpdateFleetPackageRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<FleetPackage> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<FleetPackage>.State in
      return try op._extractStatus(FleetPackage.self)
    }
    let rawOp = try await self.updateFleetPackage(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<FleetPackage>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single FleetPackage.
  ///
  /// @Snippet(path: "ConfigDelivery_DeleteFleetPackage")
  public func deleteFleetPackage(
    request: DeleteFleetPackageRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteFleetPackage(request: request, options: options)
  }

  /// Deletes a single FleetPackage.
  ///
  /// @Snippet(path: "ConfigDelivery_DeleteFleetPackage")
  public func deleteFleetPackagePollingUntilDone(
    request: DeleteFleetPackageRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteFleetPackage(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists Releases in a given project and location.
  ///
  /// @Snippet(path: "ConfigDelivery_ListReleases")
  public func listReleases(
    request: ListReleasesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConfigDeliveryV1.ListReleasesResponse {
    try await self.inner.listReleases(request: request, options: options)
  }

  /// Gets details of a single Release.
  ///
  /// @Snippet(path: "ConfigDelivery_GetRelease")
  public func getRelease(
    request: GetReleaseRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConfigDeliveryV1.Release {
    try await self.inner.getRelease(request: request, options: options)
  }

  /// Creates a new Release in a given project, location and resource bundle.
  ///
  /// @Snippet(path: "ConfigDelivery_CreateRelease")
  public func createRelease(
    request: CreateReleaseRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createRelease(request: request, options: options)
  }

  /// Creates a new Release in a given project, location and resource bundle.
  ///
  /// @Snippet(path: "ConfigDelivery_CreateRelease")
  public func createReleasePollingUntilDone(
    request: CreateReleaseRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Release> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Release>.State in
      return try op._extractStatus(Release.self)
    }
    let rawOp = try await self.createRelease(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Release>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the parameters of a single Release.
  ///
  /// @Snippet(path: "ConfigDelivery_UpdateRelease")
  public func updateRelease(
    request: UpdateReleaseRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateRelease(request: request, options: options)
  }

  /// Updates the parameters of a single Release.
  ///
  /// @Snippet(path: "ConfigDelivery_UpdateRelease")
  public func updateReleasePollingUntilDone(
    request: UpdateReleaseRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Release> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Release>.State in
      return try op._extractStatus(Release.self)
    }
    let rawOp = try await self.updateRelease(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Release>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single Release.
  ///
  /// @Snippet(path: "ConfigDelivery_DeleteRelease")
  public func deleteRelease(
    request: DeleteReleaseRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteRelease(request: request, options: options)
  }

  /// Deletes a single Release.
  ///
  /// @Snippet(path: "ConfigDelivery_DeleteRelease")
  public func deleteReleasePollingUntilDone(
    request: DeleteReleaseRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteRelease(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists Variants in a given project and location.
  ///
  /// @Snippet(path: "ConfigDelivery_ListVariants")
  public func listVariants(
    request: ListVariantsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConfigDeliveryV1.ListVariantsResponse {
    try await self.inner.listVariants(request: request, options: options)
  }

  /// Gets details of a single Variant.
  ///
  /// @Snippet(path: "ConfigDelivery_GetVariant")
  public func getVariant(
    request: GetVariantRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConfigDeliveryV1.Variant {
    try await self.inner.getVariant(request: request, options: options)
  }

  /// Creates a new Variant in a given project, location, resource bundle, and
  /// release.
  ///
  /// @Snippet(path: "ConfigDelivery_CreateVariant")
  public func createVariant(
    request: CreateVariantRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createVariant(request: request, options: options)
  }

  /// Creates a new Variant in a given project, location, resource bundle, and
  /// release.
  ///
  /// @Snippet(path: "ConfigDelivery_CreateVariant")
  public func createVariantPollingUntilDone(
    request: CreateVariantRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Variant> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Variant>.State in
      return try op._extractStatus(Variant.self)
    }
    let rawOp = try await self.createVariant(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Variant>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the parameters of a single Variant.
  ///
  /// @Snippet(path: "ConfigDelivery_UpdateVariant")
  public func updateVariant(
    request: UpdateVariantRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateVariant(request: request, options: options)
  }

  /// Updates the parameters of a single Variant.
  ///
  /// @Snippet(path: "ConfigDelivery_UpdateVariant")
  public func updateVariantPollingUntilDone(
    request: UpdateVariantRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Variant> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Variant>.State in
      return try op._extractStatus(Variant.self)
    }
    let rawOp = try await self.updateVariant(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Variant>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single Variant.
  ///
  /// @Snippet(path: "ConfigDelivery_DeleteVariant")
  public func deleteVariant(
    request: DeleteVariantRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteVariant(request: request, options: options)
  }

  /// Deletes a single Variant.
  ///
  /// @Snippet(path: "ConfigDelivery_DeleteVariant")
  public func deleteVariantPollingUntilDone(
    request: DeleteVariantRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteVariant(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists Rollouts in a given project, location, and Fleet Package.
  ///
  /// @Snippet(path: "ConfigDelivery_ListRollouts")
  public func listRollouts(
    request: ListRolloutsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConfigDeliveryV1.ListRolloutsResponse {
    try await self.inner.listRollouts(request: request, options: options)
  }

  /// Gets details of a single Rollout.
  ///
  /// @Snippet(path: "ConfigDelivery_GetRollout")
  public func getRollout(
    request: GetRolloutRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConfigDeliveryV1.Rollout {
    try await self.inner.getRollout(request: request, options: options)
  }

  /// Suspend a Rollout.
  ///
  /// @Snippet(path: "ConfigDelivery_SuspendRollout")
  public func suspendRollout(
    request: SuspendRolloutRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.suspendRollout(request: request, options: options)
  }

  /// Suspend a Rollout.
  ///
  /// @Snippet(path: "ConfigDelivery_SuspendRollout")
  public func suspendRolloutPollingUntilDone(
    request: SuspendRolloutRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Rollout> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Rollout>.State in
      return try op._extractStatus(Rollout.self)
    }
    let rawOp = try await self.suspendRollout(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Rollout>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Resume a Rollout.
  ///
  /// @Snippet(path: "ConfigDelivery_ResumeRollout")
  public func resumeRollout(
    request: ResumeRolloutRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.resumeRollout(request: request, options: options)
  }

  /// Resume a Rollout.
  ///
  /// @Snippet(path: "ConfigDelivery_ResumeRollout")
  public func resumeRolloutPollingUntilDone(
    request: ResumeRolloutRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Rollout> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Rollout>.State in
      return try op._extractStatus(Rollout.self)
    }
    let rawOp = try await self.resumeRollout(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Rollout>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Abort a Rollout.
  ///
  /// @Snippet(path: "ConfigDelivery_AbortRollout")
  public func abortRollout(
    request: AbortRolloutRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.abortRollout(request: request, options: options)
  }

  /// Abort a Rollout.
  ///
  /// @Snippet(path: "ConfigDelivery_AbortRollout")
  public func abortRolloutPollingUntilDone(
    request: AbortRolloutRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Rollout> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Rollout>.State in
      return try op._extractStatus(Rollout.self)
    }
    let rawOp = try await self.abortRollout(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Rollout>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "ConfigDelivery_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "ConfigDelivery_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ConfigDelivery_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ConfigDelivery_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ConfigDelivery_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ConfigDelivery_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ConfigDeliveryClient`.
  ///
  /// To mock `ConfigDeliveryClient` change your functions to receive
  /// `some ConfigDeliveryProtocol` or `any ConfigDeliveryProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ConfigDeliveryProtocol: Sendable {
    /// See `ConfigDeliveryClient.createResourceBundle`.
    func createResourceBundlePollingUntilDone(request: CreateResourceBundleRequest) async throws
      -> any GoogleGax.PollableOperation<ResourceBundle>

    /// See `ConfigDeliveryClient.createResourceBundle`.
    func createResourceBundlePollingUntilDone(
      parent: Swift.String,
      resourceBundle: ResourceBundle?,
      resourceBundleId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<ResourceBundle>

    /// See `ConfigDeliveryClient.updateResourceBundle`.
    func updateResourceBundlePollingUntilDone(request: UpdateResourceBundleRequest) async throws
      -> any GoogleGax.PollableOperation<ResourceBundle>

    /// See `ConfigDeliveryClient.updateResourceBundle`.
    func updateResourceBundlePollingUntilDone(
      resourceBundle: ResourceBundle?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<ResourceBundle>

    /// See `ConfigDeliveryClient.deleteResourceBundle`.
    func deleteResourceBundlePollingUntilDone(request: DeleteResourceBundleRequest) async throws
      -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `ConfigDeliveryClient.deleteResourceBundle`.
    func deleteResourceBundlePollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `ConfigDeliveryClient.createFleetPackage`.
    func createFleetPackagePollingUntilDone(request: CreateFleetPackageRequest) async throws
      -> any GoogleGax.PollableOperation<FleetPackage>

    /// See `ConfigDeliveryClient.createFleetPackage`.
    func createFleetPackagePollingUntilDone(
      parent: Swift.String,
      fleetPackage: FleetPackage?,
      fleetPackageId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<FleetPackage>

    /// See `ConfigDeliveryClient.updateFleetPackage`.
    func updateFleetPackagePollingUntilDone(request: UpdateFleetPackageRequest) async throws
      -> any GoogleGax.PollableOperation<FleetPackage>

    /// See `ConfigDeliveryClient.updateFleetPackage`.
    func updateFleetPackagePollingUntilDone(
      fleetPackage: FleetPackage?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<FleetPackage>

    /// See `ConfigDeliveryClient.deleteFleetPackage`.
    func deleteFleetPackagePollingUntilDone(request: DeleteFleetPackageRequest) async throws
      -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `ConfigDeliveryClient.deleteFleetPackage`.
    func deleteFleetPackagePollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `ConfigDeliveryClient.createRelease`.
    func createReleasePollingUntilDone(request: CreateReleaseRequest) async throws -> any GoogleGax
      .PollableOperation<Release>

    /// See `ConfigDeliveryClient.createRelease`.
    func createReleasePollingUntilDone(
      parent: Swift.String,
      release: Release?,
      releaseId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Release>

    /// See `ConfigDeliveryClient.updateRelease`.
    func updateReleasePollingUntilDone(request: UpdateReleaseRequest) async throws -> any GoogleGax
      .PollableOperation<Release>

    /// See `ConfigDeliveryClient.updateRelease`.
    func updateReleasePollingUntilDone(
      release: Release?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<Release>

    /// See `ConfigDeliveryClient.deleteRelease`.
    func deleteReleasePollingUntilDone(request: DeleteReleaseRequest) async throws -> any GoogleGax
      .PollableOperation<Swift.Void>

    /// See `ConfigDeliveryClient.deleteRelease`.
    func deleteReleasePollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `ConfigDeliveryClient.createVariant`.
    func createVariantPollingUntilDone(request: CreateVariantRequest) async throws -> any GoogleGax
      .PollableOperation<Variant>

    /// See `ConfigDeliveryClient.createVariant`.
    func createVariantPollingUntilDone(
      parent: Swift.String,
      variant: Variant?,
      variantId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Variant>

    /// See `ConfigDeliveryClient.updateVariant`.
    func updateVariantPollingUntilDone(request: UpdateVariantRequest) async throws -> any GoogleGax
      .PollableOperation<Variant>

    /// See `ConfigDeliveryClient.updateVariant`.
    func updateVariantPollingUntilDone(
      variant: Variant?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<Variant>

    /// See `ConfigDeliveryClient.deleteVariant`.
    func deleteVariantPollingUntilDone(request: DeleteVariantRequest) async throws -> any GoogleGax
      .PollableOperation<Swift.Void>

    /// See `ConfigDeliveryClient.deleteVariant`.
    func deleteVariantPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `ConfigDeliveryClient.suspendRollout`.
    func suspendRolloutPollingUntilDone(request: SuspendRolloutRequest) async throws
      -> any GoogleGax.PollableOperation<Rollout>

    /// See `ConfigDeliveryClient.suspendRollout`.
    func suspendRolloutPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Rollout>

    /// See `ConfigDeliveryClient.resumeRollout`.
    func resumeRolloutPollingUntilDone(request: ResumeRolloutRequest) async throws -> any GoogleGax
      .PollableOperation<Rollout>

    /// See `ConfigDeliveryClient.resumeRollout`.
    func resumeRolloutPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Rollout>

    /// See `ConfigDeliveryClient.abortRollout`.
    func abortRolloutPollingUntilDone(request: AbortRolloutRequest) async throws -> any GoogleGax
      .PollableOperation<Rollout>

    /// See `ConfigDeliveryClient.abortRollout`.
    func abortRolloutPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Rollout>

    /// See `ConfigDeliveryClient.listResourceBundles`.
    func listResourceBundles(
      request: ListResourceBundlesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigDeliveryV1.ListResourceBundlesResponse

    /// See `ConfigDeliveryClient.getResourceBundle`.
    func getResourceBundle(
      request: GetResourceBundleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigDeliveryV1.ResourceBundle

    /// See `ConfigDeliveryClient.createResourceBundle`.
    func createResourceBundle(
      request: CreateResourceBundleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ConfigDeliveryClient.createResourceBundle`.
    func createResourceBundlePollingUntilDone(
      request: CreateResourceBundleRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<ResourceBundle>

    /// See `ConfigDeliveryClient.updateResourceBundle`.
    func updateResourceBundle(
      request: UpdateResourceBundleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ConfigDeliveryClient.updateResourceBundle`.
    func updateResourceBundlePollingUntilDone(
      request: UpdateResourceBundleRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<ResourceBundle>

    /// See `ConfigDeliveryClient.deleteResourceBundle`.
    func deleteResourceBundle(
      request: DeleteResourceBundleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ConfigDeliveryClient.deleteResourceBundle`.
    func deleteResourceBundlePollingUntilDone(
      request: DeleteResourceBundleRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `ConfigDeliveryClient.listFleetPackages`.
    func listFleetPackages(
      request: ListFleetPackagesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigDeliveryV1.ListFleetPackagesResponse

    /// See `ConfigDeliveryClient.getFleetPackage`.
    func getFleetPackage(
      request: GetFleetPackageRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigDeliveryV1.FleetPackage

    /// See `ConfigDeliveryClient.createFleetPackage`.
    func createFleetPackage(
      request: CreateFleetPackageRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ConfigDeliveryClient.createFleetPackage`.
    func createFleetPackagePollingUntilDone(
      request: CreateFleetPackageRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<FleetPackage>

    /// See `ConfigDeliveryClient.updateFleetPackage`.
    func updateFleetPackage(
      request: UpdateFleetPackageRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ConfigDeliveryClient.updateFleetPackage`.
    func updateFleetPackagePollingUntilDone(
      request: UpdateFleetPackageRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<FleetPackage>

    /// See `ConfigDeliveryClient.deleteFleetPackage`.
    func deleteFleetPackage(
      request: DeleteFleetPackageRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ConfigDeliveryClient.deleteFleetPackage`.
    func deleteFleetPackagePollingUntilDone(
      request: DeleteFleetPackageRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `ConfigDeliveryClient.listReleases`.
    func listReleases(
      request: ListReleasesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigDeliveryV1.ListReleasesResponse

    /// See `ConfigDeliveryClient.getRelease`.
    func getRelease(
      request: GetReleaseRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigDeliveryV1.Release

    /// See `ConfigDeliveryClient.createRelease`.
    func createRelease(
      request: CreateReleaseRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ConfigDeliveryClient.createRelease`.
    func createReleasePollingUntilDone(
      request: CreateReleaseRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Release>

    /// See `ConfigDeliveryClient.updateRelease`.
    func updateRelease(
      request: UpdateReleaseRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ConfigDeliveryClient.updateRelease`.
    func updateReleasePollingUntilDone(
      request: UpdateReleaseRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Release>

    /// See `ConfigDeliveryClient.deleteRelease`.
    func deleteRelease(
      request: DeleteReleaseRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ConfigDeliveryClient.deleteRelease`.
    func deleteReleasePollingUntilDone(
      request: DeleteReleaseRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `ConfigDeliveryClient.listVariants`.
    func listVariants(
      request: ListVariantsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigDeliveryV1.ListVariantsResponse

    /// See `ConfigDeliveryClient.getVariant`.
    func getVariant(
      request: GetVariantRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigDeliveryV1.Variant

    /// See `ConfigDeliveryClient.createVariant`.
    func createVariant(
      request: CreateVariantRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ConfigDeliveryClient.createVariant`.
    func createVariantPollingUntilDone(
      request: CreateVariantRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Variant>

    /// See `ConfigDeliveryClient.updateVariant`.
    func updateVariant(
      request: UpdateVariantRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ConfigDeliveryClient.updateVariant`.
    func updateVariantPollingUntilDone(
      request: UpdateVariantRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Variant>

    /// See `ConfigDeliveryClient.deleteVariant`.
    func deleteVariant(
      request: DeleteVariantRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ConfigDeliveryClient.deleteVariant`.
    func deleteVariantPollingUntilDone(
      request: DeleteVariantRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `ConfigDeliveryClient.listRollouts`.
    func listRollouts(
      request: ListRolloutsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigDeliveryV1.ListRolloutsResponse

    /// See `ConfigDeliveryClient.getRollout`.
    func getRollout(
      request: GetRolloutRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfigDeliveryV1.Rollout

    /// See `ConfigDeliveryClient.suspendRollout`.
    func suspendRollout(
      request: SuspendRolloutRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ConfigDeliveryClient.suspendRollout`.
    func suspendRolloutPollingUntilDone(
      request: SuspendRolloutRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Rollout>

    /// See `ConfigDeliveryClient.resumeRollout`.
    func resumeRollout(
      request: ResumeRolloutRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ConfigDeliveryClient.resumeRollout`.
    func resumeRolloutPollingUntilDone(
      request: ResumeRolloutRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Rollout>

    /// See `ConfigDeliveryClient.abortRollout`.
    func abortRollout(
      request: AbortRolloutRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ConfigDeliveryClient.abortRollout`.
    func abortRolloutPollingUntilDone(
      request: AbortRolloutRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Rollout>

    /// See `ConfigDeliveryClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `ConfigDeliveryClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `ConfigDeliveryClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `ConfigDeliveryClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ConfigDeliveryClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.ConfigDeliveryProtocol {
  public func listResourceBundles(request: ListResourceBundlesRequest) async throws
    -> GoogleCloudConfigDeliveryV1.ListResourceBundlesResponse
  {
    try await self.listResourceBundles(request: request, options: .init())
  }

  public func listResourceBundles(
    request: ListResourceBundlesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConfigDeliveryV1.ListResourceBundlesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listResourceBundlesByItems(
    request: ListResourceBundlesRequest
  ) -> any AsyncSequence<ResourceBundle, Swift.Error> & Sendable {
    self.listResourceBundlesByItems(request: request, options: .init())
  }

  /// Lists ResourceBundles in a given project and location.
  ///
  /// @Snippet(path: "ConfigDelivery_ListResourceBundles")
  public func listResourceBundlesByItems(
    request: ListResourceBundlesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<ResourceBundle, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudConfigDeliveryV1.ListResourceBundlesResponse in
      var request = request
      request.pageToken = token
      return try await self.listResourceBundles(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listResourceBundlesByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<ResourceBundle, Swift.Error> & Sendable {
    let request = ListResourceBundlesRequest().with {
      $0.parent = parent
    }
    return self.listResourceBundlesByItems(request: request)
  }

  public func getResourceBundle(request: GetResourceBundleRequest) async throws
    -> GoogleCloudConfigDeliveryV1.ResourceBundle
  {
    try await self.getResourceBundle(request: request, options: .init())
  }

  public func getResourceBundle(
    request: GetResourceBundleRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConfigDeliveryV1.ResourceBundle {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getResourceBundle(
    name: Swift.String,
  ) async throws -> GoogleCloudConfigDeliveryV1.ResourceBundle {
    let request = GetResourceBundleRequest().with {
      $0.name = name
    }
    return try await self.getResourceBundle(request: request)
  }

  public func createResourceBundle(request: CreateResourceBundleRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createResourceBundle(request: request, options: .init())
  }

  public func createResourceBundle(
    request: CreateResourceBundleRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createResourceBundlePollingUntilDone(request: CreateResourceBundleRequest)
    async throws -> any GoogleGax.PollableOperation<ResourceBundle>
  {
    try await self.createResourceBundlePollingUntilDone(request: request, options: .init())
  }

  public func createResourceBundlePollingUntilDone(
    request: CreateResourceBundleRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<ResourceBundle> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<ResourceBundle>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createResourceBundlePollingUntilDone(
    parent: Swift.String,
    resourceBundle: ResourceBundle?,
    resourceBundleId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<ResourceBundle> {
    let request = CreateResourceBundleRequest().with {
      $0.parent = parent
      $0.resourceBundle = resourceBundle
      $0.resourceBundleId = resourceBundleId
    }
    return try await self.createResourceBundlePollingUntilDone(request: request)
  }

  public func updateResourceBundle(request: UpdateResourceBundleRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateResourceBundle(request: request, options: .init())
  }

  public func updateResourceBundle(
    request: UpdateResourceBundleRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateResourceBundlePollingUntilDone(request: UpdateResourceBundleRequest)
    async throws -> any GoogleGax.PollableOperation<ResourceBundle>
  {
    try await self.updateResourceBundlePollingUntilDone(request: request, options: .init())
  }

  public func updateResourceBundlePollingUntilDone(
    request: UpdateResourceBundleRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<ResourceBundle> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<ResourceBundle>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateResourceBundlePollingUntilDone(
    resourceBundle: ResourceBundle?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<ResourceBundle> {
    let request = UpdateResourceBundleRequest().with {
      $0.resourceBundle = resourceBundle
      $0.updateMask = updateMask
    }
    return try await self.updateResourceBundlePollingUntilDone(request: request)
  }

  public func deleteResourceBundle(request: DeleteResourceBundleRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteResourceBundle(request: request, options: .init())
  }

  public func deleteResourceBundle(
    request: DeleteResourceBundleRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteResourceBundlePollingUntilDone(request: DeleteResourceBundleRequest)
    async throws -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteResourceBundlePollingUntilDone(request: request, options: .init())
  }

  public func deleteResourceBundlePollingUntilDone(
    request: DeleteResourceBundleRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteResourceBundlePollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteResourceBundleRequest().with {
      $0.name = name
    }
    return try await self.deleteResourceBundlePollingUntilDone(request: request)
  }

  public func listFleetPackages(request: ListFleetPackagesRequest) async throws
    -> GoogleCloudConfigDeliveryV1.ListFleetPackagesResponse
  {
    try await self.listFleetPackages(request: request, options: .init())
  }

  public func listFleetPackages(
    request: ListFleetPackagesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConfigDeliveryV1.ListFleetPackagesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listFleetPackagesByItems(
    request: ListFleetPackagesRequest
  ) -> any AsyncSequence<FleetPackage, Swift.Error> & Sendable {
    self.listFleetPackagesByItems(request: request, options: .init())
  }

  /// Lists FleetPackages in a given project and location.
  ///
  /// @Snippet(path: "ConfigDelivery_ListFleetPackages")
  public func listFleetPackagesByItems(
    request: ListFleetPackagesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<FleetPackage, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudConfigDeliveryV1.ListFleetPackagesResponse in
      var request = request
      request.pageToken = token
      return try await self.listFleetPackages(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listFleetPackagesByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<FleetPackage, Swift.Error> & Sendable {
    let request = ListFleetPackagesRequest().with {
      $0.parent = parent
    }
    return self.listFleetPackagesByItems(request: request)
  }

  public func getFleetPackage(request: GetFleetPackageRequest) async throws
    -> GoogleCloudConfigDeliveryV1.FleetPackage
  {
    try await self.getFleetPackage(request: request, options: .init())
  }

  public func getFleetPackage(
    request: GetFleetPackageRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConfigDeliveryV1.FleetPackage {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getFleetPackage(
    name: Swift.String,
  ) async throws -> GoogleCloudConfigDeliveryV1.FleetPackage {
    let request = GetFleetPackageRequest().with {
      $0.name = name
    }
    return try await self.getFleetPackage(request: request)
  }

  public func createFleetPackage(request: CreateFleetPackageRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createFleetPackage(request: request, options: .init())
  }

  public func createFleetPackage(
    request: CreateFleetPackageRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createFleetPackagePollingUntilDone(request: CreateFleetPackageRequest) async throws
    -> any GoogleGax.PollableOperation<FleetPackage>
  {
    try await self.createFleetPackagePollingUntilDone(request: request, options: .init())
  }

  public func createFleetPackagePollingUntilDone(
    request: CreateFleetPackageRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<FleetPackage> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<FleetPackage>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createFleetPackagePollingUntilDone(
    parent: Swift.String,
    fleetPackage: FleetPackage?,
    fleetPackageId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<FleetPackage> {
    let request = CreateFleetPackageRequest().with {
      $0.parent = parent
      $0.fleetPackage = fleetPackage
      $0.fleetPackageId = fleetPackageId
    }
    return try await self.createFleetPackagePollingUntilDone(request: request)
  }

  public func updateFleetPackage(request: UpdateFleetPackageRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateFleetPackage(request: request, options: .init())
  }

  public func updateFleetPackage(
    request: UpdateFleetPackageRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateFleetPackagePollingUntilDone(request: UpdateFleetPackageRequest) async throws
    -> any GoogleGax.PollableOperation<FleetPackage>
  {
    try await self.updateFleetPackagePollingUntilDone(request: request, options: .init())
  }

  public func updateFleetPackagePollingUntilDone(
    request: UpdateFleetPackageRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<FleetPackage> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<FleetPackage>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateFleetPackagePollingUntilDone(
    fleetPackage: FleetPackage?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<FleetPackage> {
    let request = UpdateFleetPackageRequest().with {
      $0.fleetPackage = fleetPackage
      $0.updateMask = updateMask
    }
    return try await self.updateFleetPackagePollingUntilDone(request: request)
  }

  public func deleteFleetPackage(request: DeleteFleetPackageRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteFleetPackage(request: request, options: .init())
  }

  public func deleteFleetPackage(
    request: DeleteFleetPackageRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteFleetPackagePollingUntilDone(request: DeleteFleetPackageRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteFleetPackagePollingUntilDone(request: request, options: .init())
  }

  public func deleteFleetPackagePollingUntilDone(
    request: DeleteFleetPackageRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteFleetPackagePollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteFleetPackageRequest().with {
      $0.name = name
    }
    return try await self.deleteFleetPackagePollingUntilDone(request: request)
  }

  public func listReleases(request: ListReleasesRequest) async throws
    -> GoogleCloudConfigDeliveryV1.ListReleasesResponse
  {
    try await self.listReleases(request: request, options: .init())
  }

  public func listReleases(
    request: ListReleasesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConfigDeliveryV1.ListReleasesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listReleasesByItems(
    request: ListReleasesRequest
  ) -> any AsyncSequence<Release, Swift.Error> & Sendable {
    self.listReleasesByItems(request: request, options: .init())
  }

  /// Lists Releases in a given project and location.
  ///
  /// @Snippet(path: "ConfigDelivery_ListReleases")
  public func listReleasesByItems(
    request: ListReleasesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Release, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudConfigDeliveryV1.ListReleasesResponse in
      var request = request
      request.pageToken = token
      return try await self.listReleases(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listReleasesByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Release, Swift.Error> & Sendable {
    let request = ListReleasesRequest().with {
      $0.parent = parent
    }
    return self.listReleasesByItems(request: request)
  }

  public func getRelease(request: GetReleaseRequest) async throws
    -> GoogleCloudConfigDeliveryV1.Release
  {
    try await self.getRelease(request: request, options: .init())
  }

  public func getRelease(
    request: GetReleaseRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConfigDeliveryV1.Release {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getRelease(
    name: Swift.String,
  ) async throws -> GoogleCloudConfigDeliveryV1.Release {
    let request = GetReleaseRequest().with {
      $0.name = name
    }
    return try await self.getRelease(request: request)
  }

  public func createRelease(request: CreateReleaseRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createRelease(request: request, options: .init())
  }

  public func createRelease(
    request: CreateReleaseRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createReleasePollingUntilDone(request: CreateReleaseRequest) async throws
    -> any GoogleGax.PollableOperation<Release>
  {
    try await self.createReleasePollingUntilDone(request: request, options: .init())
  }

  public func createReleasePollingUntilDone(
    request: CreateReleaseRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Release> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Release>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createReleasePollingUntilDone(
    parent: Swift.String,
    release: Release?,
    releaseId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Release> {
    let request = CreateReleaseRequest().with {
      $0.parent = parent
      $0.release = release
      $0.releaseId = releaseId
    }
    return try await self.createReleasePollingUntilDone(request: request)
  }

  public func updateRelease(request: UpdateReleaseRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateRelease(request: request, options: .init())
  }

  public func updateRelease(
    request: UpdateReleaseRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateReleasePollingUntilDone(request: UpdateReleaseRequest) async throws
    -> any GoogleGax.PollableOperation<Release>
  {
    try await self.updateReleasePollingUntilDone(request: request, options: .init())
  }

  public func updateReleasePollingUntilDone(
    request: UpdateReleaseRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Release> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Release>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateReleasePollingUntilDone(
    release: Release?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Release> {
    let request = UpdateReleaseRequest().with {
      $0.release = release
      $0.updateMask = updateMask
    }
    return try await self.updateReleasePollingUntilDone(request: request)
  }

  public func deleteRelease(request: DeleteReleaseRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteRelease(request: request, options: .init())
  }

  public func deleteRelease(
    request: DeleteReleaseRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteReleasePollingUntilDone(request: DeleteReleaseRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteReleasePollingUntilDone(request: request, options: .init())
  }

  public func deleteReleasePollingUntilDone(
    request: DeleteReleaseRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteReleasePollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteReleaseRequest().with {
      $0.name = name
    }
    return try await self.deleteReleasePollingUntilDone(request: request)
  }

  public func listVariants(request: ListVariantsRequest) async throws
    -> GoogleCloudConfigDeliveryV1.ListVariantsResponse
  {
    try await self.listVariants(request: request, options: .init())
  }

  public func listVariants(
    request: ListVariantsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConfigDeliveryV1.ListVariantsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listVariantsByItems(
    request: ListVariantsRequest
  ) -> any AsyncSequence<Variant, Swift.Error> & Sendable {
    self.listVariantsByItems(request: request, options: .init())
  }

  /// Lists Variants in a given project and location.
  ///
  /// @Snippet(path: "ConfigDelivery_ListVariants")
  public func listVariantsByItems(
    request: ListVariantsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Variant, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudConfigDeliveryV1.ListVariantsResponse in
      var request = request
      request.pageToken = token
      return try await self.listVariants(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listVariantsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Variant, Swift.Error> & Sendable {
    let request = ListVariantsRequest().with {
      $0.parent = parent
    }
    return self.listVariantsByItems(request: request)
  }

  public func getVariant(request: GetVariantRequest) async throws
    -> GoogleCloudConfigDeliveryV1.Variant
  {
    try await self.getVariant(request: request, options: .init())
  }

  public func getVariant(
    request: GetVariantRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConfigDeliveryV1.Variant {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getVariant(
    name: Swift.String,
  ) async throws -> GoogleCloudConfigDeliveryV1.Variant {
    let request = GetVariantRequest().with {
      $0.name = name
    }
    return try await self.getVariant(request: request)
  }

  public func createVariant(request: CreateVariantRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createVariant(request: request, options: .init())
  }

  public func createVariant(
    request: CreateVariantRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createVariantPollingUntilDone(request: CreateVariantRequest) async throws
    -> any GoogleGax.PollableOperation<Variant>
  {
    try await self.createVariantPollingUntilDone(request: request, options: .init())
  }

  public func createVariantPollingUntilDone(
    request: CreateVariantRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Variant> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Variant>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createVariantPollingUntilDone(
    parent: Swift.String,
    variant: Variant?,
    variantId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Variant> {
    let request = CreateVariantRequest().with {
      $0.parent = parent
      $0.variant = variant
      $0.variantId = variantId
    }
    return try await self.createVariantPollingUntilDone(request: request)
  }

  public func updateVariant(request: UpdateVariantRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateVariant(request: request, options: .init())
  }

  public func updateVariant(
    request: UpdateVariantRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateVariantPollingUntilDone(request: UpdateVariantRequest) async throws
    -> any GoogleGax.PollableOperation<Variant>
  {
    try await self.updateVariantPollingUntilDone(request: request, options: .init())
  }

  public func updateVariantPollingUntilDone(
    request: UpdateVariantRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Variant> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Variant>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateVariantPollingUntilDone(
    variant: Variant?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Variant> {
    let request = UpdateVariantRequest().with {
      $0.variant = variant
      $0.updateMask = updateMask
    }
    return try await self.updateVariantPollingUntilDone(request: request)
  }

  public func deleteVariant(request: DeleteVariantRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteVariant(request: request, options: .init())
  }

  public func deleteVariant(
    request: DeleteVariantRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteVariantPollingUntilDone(request: DeleteVariantRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteVariantPollingUntilDone(request: request, options: .init())
  }

  public func deleteVariantPollingUntilDone(
    request: DeleteVariantRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteVariantPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteVariantRequest().with {
      $0.name = name
    }
    return try await self.deleteVariantPollingUntilDone(request: request)
  }

  public func listRollouts(request: ListRolloutsRequest) async throws
    -> GoogleCloudConfigDeliveryV1.ListRolloutsResponse
  {
    try await self.listRollouts(request: request, options: .init())
  }

  public func listRollouts(
    request: ListRolloutsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConfigDeliveryV1.ListRolloutsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listRolloutsByItems(
    request: ListRolloutsRequest
  ) -> any AsyncSequence<Rollout, Swift.Error> & Sendable {
    self.listRolloutsByItems(request: request, options: .init())
  }

  /// Lists Rollouts in a given project, location, and Fleet Package.
  ///
  /// @Snippet(path: "ConfigDelivery_ListRollouts")
  public func listRolloutsByItems(
    request: ListRolloutsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Rollout, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudConfigDeliveryV1.ListRolloutsResponse in
      var request = request
      request.pageToken = token
      return try await self.listRollouts(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listRolloutsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Rollout, Swift.Error> & Sendable {
    let request = ListRolloutsRequest().with {
      $0.parent = parent
    }
    return self.listRolloutsByItems(request: request)
  }

  public func getRollout(request: GetRolloutRequest) async throws
    -> GoogleCloudConfigDeliveryV1.Rollout
  {
    try await self.getRollout(request: request, options: .init())
  }

  public func getRollout(
    request: GetRolloutRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConfigDeliveryV1.Rollout {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getRollout(
    name: Swift.String,
  ) async throws -> GoogleCloudConfigDeliveryV1.Rollout {
    let request = GetRolloutRequest().with {
      $0.name = name
    }
    return try await self.getRollout(request: request)
  }

  public func suspendRollout(request: SuspendRolloutRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.suspendRollout(request: request, options: .init())
  }

  public func suspendRollout(
    request: SuspendRolloutRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func suspendRolloutPollingUntilDone(request: SuspendRolloutRequest) async throws
    -> any GoogleGax.PollableOperation<Rollout>
  {
    try await self.suspendRolloutPollingUntilDone(request: request, options: .init())
  }

  public func suspendRolloutPollingUntilDone(
    request: SuspendRolloutRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Rollout> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Rollout>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func suspendRolloutPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Rollout> {
    let request = SuspendRolloutRequest().with {
      $0.name = name
    }
    return try await self.suspendRolloutPollingUntilDone(request: request)
  }

  public func resumeRollout(request: ResumeRolloutRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.resumeRollout(request: request, options: .init())
  }

  public func resumeRollout(
    request: ResumeRolloutRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func resumeRolloutPollingUntilDone(request: ResumeRolloutRequest) async throws
    -> any GoogleGax.PollableOperation<Rollout>
  {
    try await self.resumeRolloutPollingUntilDone(request: request, options: .init())
  }

  public func resumeRolloutPollingUntilDone(
    request: ResumeRolloutRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Rollout> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Rollout>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func resumeRolloutPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Rollout> {
    let request = ResumeRolloutRequest().with {
      $0.name = name
    }
    return try await self.resumeRolloutPollingUntilDone(request: request)
  }

  public func abortRollout(request: AbortRolloutRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.abortRollout(request: request, options: .init())
  }

  public func abortRollout(
    request: AbortRolloutRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func abortRolloutPollingUntilDone(request: AbortRolloutRequest) async throws
    -> any GoogleGax.PollableOperation<Rollout>
  {
    try await self.abortRolloutPollingUntilDone(request: request, options: .init())
  }

  public func abortRolloutPollingUntilDone(
    request: AbortRolloutRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Rollout> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Rollout>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func abortRolloutPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Rollout> {
    let request = AbortRolloutRequest().with {
      $0.name = name
    }
    return try await self.abortRolloutPollingUntilDone(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "ConfigDelivery_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ConfigDelivery_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
