// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// ResourceBundleDeploymentInfo represents the status of a resource bundle
/// deployment.
public struct ResourceBundleDeploymentInfo: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Refers to a `ResourceBundle` release.
  public var release: Swift.String = Swift.String()

  /// Output only. Refers to a version of the `ResourceBundle` release.
  public var version: Swift.String = Swift.String()

  /// Output only. Refers to a variant in a `ResourceBundle` release.
  public var variant: Swift.String = Swift.String()

  /// Output only. Synchronization state of the `ResourceBundle` deployment.
  public var syncState: ResourceBundleDeploymentInfo.SyncState =
    ResourceBundleDeploymentInfo.SyncState()

  /// Output only. Unordered list. Messages contains information related to the
  /// `ResourceBundle` deployment. For example, in case of an error, indicate the
  /// reason for the error. In case of a pending deployment, reason for why the
  /// deployment of new release is pending.
  public var messages: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ResourceBundleDeploymentInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ResourceBundleDeploymentInfo().with { $0.release = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let release = CodingKeys(stringValue: "release")
    static let version = CodingKeys(stringValue: "version")
    static let variant = CodingKeys(stringValue: "variant")
    static let syncState = CodingKeys(stringValue: "syncState")
    static let messages = CodingKeys(stringValue: "messages")

    static let _knownKeys: Set<Swift.String> = [
      "release",
      "version",
      "variant",
      "syncState",
      "messages",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .release) {
      self.release = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .version) {
      self.version = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .variant) {
      self.variant = value
    }
    if let value = try container.decodeIfPresent(
      ResourceBundleDeploymentInfo.SyncState.self, forKey: .syncState)
    {
      self.syncState = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .messages) {
      self.messages = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.release, forKey: .release)
    try container.encode(self.version, forKey: .version)
    try container.encode(self.variant, forKey: .variant)
    try container.encode(self.syncState, forKey: .syncState)
    try container.encode(self.messages, forKey: .messages)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Synchronization state of the resource bundle deployment.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum SyncState: Codable, Equatable, Sendable {
    /// Unspecified state.
    case unspecified
    /// Reconciling state.
    case reconciling
    /// Stalled state.
    case stalled
    /// Synced state.
    case synced
    /// Pending state.
    case pending
    /// Error state.
    case error
    /// Deletion pending state.
    case deletionPending
    /// Deleting state.
    case deleting
    /// Deleted state.
    case deleted
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .reconciling: return 1
      case .stalled: return 2
      case .synced: return 3
      case .pending: return 4
      case .error: return 5
      case .deletionPending: return 6
      case .deleting: return 7
      case .deleted: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SYNC_STATE_UNSPECIFIED"
      case .reconciling: return "RECONCILING"
      case .stalled: return "STALLED"
      case .synced: return "SYNCED"
      case .pending: return "PENDING"
      case .error: return "ERROR"
      case .deletionPending: return "DELETION_PENDING"
      case .deleting: return "DELETING"
      case .deleted: return "DELETED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SyncState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SYNC_STATE_UNSPECIFIED": self = .unspecified
      case "RECONCILING": self = .reconciling
      case "STALLED": self = .stalled
      case "SYNCED": self = .synced
      case "PENDING": self = .pending
      case "ERROR": self = .error
      case "DELETION_PENDING": self = .deletionPending
      case "DELETING": self = .deleting
      case "DELETED": self = .deleted
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SyncState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .reconciling
      case 2: self = .stalled
      case 3: self = .synced
      case 4: self = .pending
      case 5: self = .error
      case 6: self = .deletionPending
      case 7: self = .deleting
      case 8: self = .deleted
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("SYNC_STATE_UNSPECIFIED")
      case .reconciling: return try container.encode("RECONCILING")
      case .stalled: return try container.encode("STALLED")
      case .synced: return try container.encode("SYNCED")
      case .pending: return try container.encode("PENDING")
      case .error: return try container.encode("ERROR")
      case .deletionPending: return try container.encode("DELETION_PENDING")
      case .deleting: return try container.encode("DELETING")
      case .deleted: return try container.encode("DELETED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.configdelivery.v1.ResourceBundleDeploymentInfo"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
