// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// RolloutStrategyInfo represents the status of execution of different types of
/// rollout strategies. Only the field corresponding to the rollout strategy
/// specified at the rollout resource will be populated.
public struct RolloutStrategyInfo: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// strategy represents result of applying one of the rollout strategies.
  public var strategy: OneOf_Strategy? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RolloutStrategyInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RolloutStrategyInfo().with { $0.allAtOnceStrategyInfo = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let allAtOnceStrategyInfo = CodingKeys(stringValue: "allAtOnceStrategyInfo")
    static let rollingStrategyInfo = CodingKeys(stringValue: "rollingStrategyInfo")

    static let _knownKeys: Set<Swift.String> = [
      "allAtOnceStrategyInfo",
      "rollingStrategyInfo",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var strategy: OneOf_Strategy? = nil
    let strategyCheckAndSet = {
      if strategy != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'strategy'"))
      }
      strategy = $0
    }
    if let allAtOnceStrategyInfo = try container.decodeIfPresent(
      AllAtOnceStrategyInfo?.self, forKey: .allAtOnceStrategyInfo)
    {
      try strategyCheckAndSet(.allAtOnceStrategyInfo(allAtOnceStrategyInfo))
    }
    if let rollingStrategyInfo = try container.decodeIfPresent(
      RollingStrategyInfo?.self, forKey: .rollingStrategyInfo)
    {
      try strategyCheckAndSet(.rollingStrategyInfo(rollingStrategyInfo))
    }
    self.strategy = strategy
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.strategy {
      switch choice {
      case .allAtOnceStrategyInfo(let value):
        try container.encode(value, forKey: .allAtOnceStrategyInfo)
      case .rollingStrategyInfo(let value):
        try container.encode(value, forKey: .rollingStrategyInfo)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// strategy represents result of applying one of the rollout strategies.
  public enum OneOf_Strategy: Codable, Equatable, Sendable {
    /// AllAtOnceStrategyInfo represents the status of AllAtOnce rollout strategy
    /// execution.
    indirect case allAtOnceStrategyInfo(AllAtOnceStrategyInfo?)
    /// RollingStrategyInfo represents the status of Rolling rollout strategy
    /// execution.
    indirect case rollingStrategyInfo(RollingStrategyInfo?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.configdelivery.v1.RolloutStrategyInfo"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
