// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Rollout resource represents an instance of `FleetPackage` rollout operation
/// across a fleet. This is a system generated resource and will be read only for
/// end-users. It will be primarily used by the service to process the changes in
/// the `FleetPackage` and other changes in the environment.
public struct Rollout: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. Name of the Rollout. Format is
  /// `projects/{project}/locations/{location}/fleetPackages/{fleet_package}/rollouts/[a-z][a-z0-9\-]{0,62}`.
  public var name: Swift.String = Swift.String()

  /// Reference to the `Release` being rolled out.
  public var release: Swift.String = Swift.String()

  /// Rollout strategy for rolling out `FleetPackage` to clusters.
  public var rolloutStrategy: RolloutStrategy? = nil

  /// Current details of the rollout.
  public var info: RolloutInfo? = nil

  /// Deletion propagation policy of the rollout.
  public var deletionPropagationPolicy: DeletionPropagationPolicy = DeletionPropagationPolicy()

  /// Output only. The time the rollout was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time the rollout was most recently updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Rollout`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Rollout().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let release = CodingKeys(stringValue: "release")
    static let rolloutStrategy = CodingKeys(stringValue: "rolloutStrategy")
    static let info = CodingKeys(stringValue: "info")
    static let deletionPropagationPolicy = CodingKeys(stringValue: "deletionPropagationPolicy")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "release",
      "rolloutStrategy",
      "info",
      "deletionPropagationPolicy",
      "createTime",
      "updateTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .release) {
      self.release = value
    }
    self.rolloutStrategy = try container.decodeIfPresent(
      RolloutStrategy.self, forKey: .rolloutStrategy)
    self.info = try container.decodeIfPresent(RolloutInfo.self, forKey: .info)
    if let value = try container.decodeIfPresent(
      DeletionPropagationPolicy.self, forKey: .deletionPropagationPolicy)
    {
      self.deletionPropagationPolicy = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.release, forKey: .release)
    try container.encodeIfPresent(self.rolloutStrategy, forKey: .rolloutStrategy)
    try container.encodeIfPresent(self.info, forKey: .info)
    try container.encode(self.deletionPropagationPolicy, forKey: .deletionPropagationPolicy)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.configdelivery.v1.Rollout"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
