// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// RolloutInfo represents the state of the `FleetPackage` at all the
/// clusters the rollout is targeting.
public struct RolloutInfo: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. state contains the overall status of the Rollout.
  public var state: RolloutInfo.State = RolloutInfo.State()

  /// Output only. Time when the rollout started.
  public var startTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Time when the rollout completed.
  public var endTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Message containing additional information related to the
  /// rollout.
  public var message: Swift.String = Swift.String()

  /// Output only. Rollout strategy info represents the status of execution of
  /// rollout strategy.
  public var rolloutStrategyInfo: RolloutStrategyInfo? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RolloutInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RolloutInfo().with { $0.state = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let state = CodingKeys(stringValue: "state")
    static let startTime = CodingKeys(stringValue: "startTime")
    static let endTime = CodingKeys(stringValue: "endTime")
    static let message = CodingKeys(stringValue: "message")
    static let rolloutStrategyInfo = CodingKeys(stringValue: "rolloutStrategyInfo")

    static let _knownKeys: Set<Swift.String> = [
      "state",
      "startTime",
      "endTime",
      "message",
      "rolloutStrategyInfo",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(RolloutInfo.State.self, forKey: .state) {
      self.state = value
    }
    self.startTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .startTime)
    self.endTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .endTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .message) {
      self.message = value
    }
    self.rolloutStrategyInfo = try container.decodeIfPresent(
      RolloutStrategyInfo.self, forKey: .rolloutStrategyInfo)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.state, forKey: .state)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    try container.encode(self.message, forKey: .message)
    try container.encodeIfPresent(self.rolloutStrategyInfo, forKey: .rolloutStrategyInfo)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// State of the rollout
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified state.
    case unspecified
    /// Rollout completed.
    case completed
    /// Rollout suspended.
    case suspended
    /// Rollout aborted.
    case aborted
    /// Rollout in progress.
    case inProgress
    /// Rollout stalled.
    case stalled
    /// Rollout cancelled.
    case cancelled
    /// Rollout aborting.
    case aborting
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .completed: return 1
      case .suspended: return 2
      case .aborted: return 3
      case .inProgress: return 5
      case .stalled: return 6
      case .cancelled: return 7
      case .aborting: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .completed: return "COMPLETED"
      case .suspended: return "SUSPENDED"
      case .aborted: return "ABORTED"
      case .inProgress: return "IN_PROGRESS"
      case .stalled: return "STALLED"
      case .cancelled: return "CANCELLED"
      case .aborting: return "ABORTING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "COMPLETED": self = .completed
      case "SUSPENDED": self = .suspended
      case "ABORTED": self = .aborted
      case "IN_PROGRESS": self = .inProgress
      case "STALLED": self = .stalled
      case "CANCELLED": self = .cancelled
      case "ABORTING": self = .aborting
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .completed
      case 2: self = .suspended
      case 3: self = .aborted
      case 5: self = .inProgress
      case 6: self = .stalled
      case 7: self = .cancelled
      case 8: self = .aborting
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .completed: return try container.encode("COMPLETED")
      case .suspended: return try container.encode("SUSPENDED")
      case .aborted: return try container.encode("ABORTED")
      case .inProgress: return try container.encode("IN_PROGRESS")
      case .stalled: return try container.encode("STALLED")
      case .cancelled: return try container.encode("CANCELLED")
      case .aborting: return try container.encode("ABORTING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.configdelivery.v1.RolloutInfo"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
